### ISSUE TITLE
Setup of kanban board

### ISSUE THREAD

**Issue by Jolak5** [Jolak5/Catalog-Ruby#28]
Link to Kanban project - https://github.com/Jolak5/Catalog-Ruby/projects/1.

We are three in this group
Team member 1 - Enis Memic: @enis-memic 
Team member 2 -  Progress Ezeamaka: @Progress2002 
Team member 3 - Kayode Joseph Olatunji: @Jolak5

**Comment by AlphaNtihinduka** [comment]
## Hello Team🙋‍♂️
Good job working on implementing the Kanban board. You have done incredibly well. 👏  

TO HIGHLIGHT:
- Fair distribution of the card tasks ✔️ 
- Assigned the group tasks to all the members ✔️ 

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Required changes :recycle: 
- [ ] You have done very great to use the Ruby kanban board template provided. However, according to the [project requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/setup_kanban_board.md#project-requirements) should be fairly distributed with least than 5 points range difference. I have noticed that @enis-memic , @Progress2002 , and @Jolak5 have 7, 8, and 2 points respectively. Kindly ensure that @Jolak5 has been assigned the tasks fairly to have points close to other team members ☺️ .

## Optional suggestions
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

**Comment by mckent05** [comment]
Hi team, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to start your capstone 👍 👍 : 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All tasks have been fairly assigned ✔️ ✔️ 
- You have correctly set up your Kanban board 👍 👍  

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
